management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024
    port: 9000
    servlet:
        session:
            timeout: 60m
    session:
        timeout: 60m
spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    resources:
        cache:
            cachecontrol:
                max-age: 120
                must-revalidate: true
