automationTestingMode: false
envName: LOCAL
google:
    recaptcha:
        key:
            secret: '{cipher}59d85162b294264a7b7c0348d45d442b65edc642c3606e27858e1c2d7bd9fc16f75c9ea0be2a246fba80e255d84bc18429227a0c6194efda89efa31da91346fd'
            site: '{cipher}49353b37247b08e2e450e18f4a5e84ad13cee80ebf81254d6a6c879701e1536a789f069d0940d7e3c7646f7eb485c663bd4be5aef91e481e2cdcccba31978ac3'
            threshold: 0.5
logging:
    file: logs/webApp/webApp.log
    pattern:
        console: '"%d{yyyy-MM-dd HH:mm:ss} - %msg%n"'
        file: '"%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"'
maintenanceMode: false
management:
    endpoints:
        web:
            exposure:
                include: '*'
security:
    require-ssl: false
server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024
    port: 9000
    servlet:
        session:
            timeout: 60m
    session:
        timeout: 60m
showContextBarDetailRow: true
spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    resources:
        cache:
            cachecontrol:
                max-age: 120
                must-revalidate: true
warning:
    before:
        timeout:
            minutes: 5
