sendCoachingMaterialEmails: false
sendGameAdvisoryEmails: false
sendPracticeAdvisoryEmails: false
sendgrid:
    webhook:
        key:'{ciperh}MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+ixKxy5yR4qHuuIPib/hBfJuoCHk7SvJHstmqbcXlyv6VJewL/3Cs6mlIMGTj81Q2NAevuKeIpRe83uh07Ai6w=='
cust:
    var:
        batchAddr: http://programandregistration.production.coachspan.internal:9015/api/v1
        coachRegistrationAddr: http://programandregistration.production.coachspan.internal:9013/api/v1
        contactLookupAddr: http://staticComboServer.production.coachspan.internal:9006/
        contentLookupAddr: http://staticComboServer.production.coachspan.internal:9010/api/v1/
        designLookupAddr: http://staticComboServer.production.coachspan.internal:9008/
        divisionAddr: http://divisionServer.production.coachspan.internal:9004/
        emailAddr: http://programandregistration.production.coachspan.internal:9999
        leagueAddr: http://smallServiceComboServer.production.coachspan.internal:9009/
        orgAddr: http://smallServiceComboServer.production.coachspan.internal:9007/
        personAddr: http://personServer.production.coachspan.internal:9002/
        programAddr: http://programandregistration.production.coachspan.internal:9012/api/v1
        programAddrv2: http://programandregistration.production.coachspan.internal:9012/api/v2
        seasonAddr: http://seasonServer.production.coachspan.internal:9005/
        seasonAddrV2: http://seasonServer.production.coachspan.internal:9005/api/v2
        trainingAddr: http://trainingServer.production.coachspan.internal:9011/
division:
    service:
        endpoint: http://divisionServer.production.coachspan.internal:9004
email:
    service:
        endpoint: http://programandregistration.production.coachspan.internal:9999
los:
    service:
        endpoint: http://programandregistration.production.coachspan.internal:9012/api/v1/los
org:
    service:
        endpoint: http://smallServiceComboServer.production.coachspan.internal:9007/
person:
    service:
        endpoint: http://personServer.production.coachspan.internal:9002
program:
    service:
        endpoint: http://programandregistration.production.coachspan.internal:9012
registration:
    service:
        endpoint: http://programandregistration.production.coachspan.internal:9013/api
        v2:
            endpoint: http://programandregistration.production.coachspan.internal:9013/api/v2
season:
    service:
        endpoint: http://seasonServer.production.coachspan.internal:9005
trainingSync:
    service:
        endpoint: http://trainingServer.production.coachspan.internal:9011
utility:
    service:
        endpoint: http://programandregistration.production.coachspan.internal:9999/api/v1
