sendCoachingMaterialEmails: true
sendGameAdvisoryEmails: true
sendPracticeAdvisoryEmails: false
sendgrid:
    webhook:
        key: '{cipher}b7cba1ef379f580e0bbc1d0c6c5321fe5913a206de4995117f180e8373d2bd0bce00a9a5647151d07a399d857affd065d895abfadd4b4b079ad86a8b6a5d8165c9e2ccf7a258861da55d7f00f12adaca721b3dfe69ff319d2f98c57a394d55f6997e8b395221c89cdcac7fec3bce1b4ff01419b8baf300f89c332f8baa18cc4e4688f8fd1e7110634f3f364b37c22921'
cust:
    var:
        batchAddr: http://localhost:9015/api/v1
        coachRegistrationAddr: http://localhost:9013/api/v1
        contactLookupAddr: http://localhost:9006/
        contentLookupAddr: http://localhost:9010/api/v1/
        designLookupAddr: http://localhost:9008/
        divisionAddr: http://localhost:9004/
        emailAddr: http://localhost:9999
        leagueAddr: http://localhost:9009/
        orgAddr: http://localhost:9007/
        personAddr: http://localhost:9002/
        programAddr: http://localhost:9012/api/v1
        programAddrv2: http://localhost:9012/api/v2
        seasonAddr: http://localhost:9005/
        seasonAddrV2: http://localhost:9005/api/v2
        trainingAddr: http://localhost:9011/
division:
    service:
        endpoint: http://localhost:9004
email:
    service:
        endpoint: http://localhost:9999
los:
    service:
        endpoint: http://localhost:9012/api/v1/los
org:
    service:
        endpoint: http://localhost:9007/
person:
    service:
        endpoint: http://localhost:9002
program:
    service:
        endpoint: http://localhost:9012
registration:
    service:
        endpoint: http://localhost:9013/api
        v2:
            endpoint: http://localhost:9013/api/v2
season:
    service:
        endpoint: http://localhost:9005
trainingSync:
    service:
        endpoint: http://localhost:9011
utility:
    service:
        endpoint: http://localhost:9999/api/v1
